server:
  port: 8100
spring:
  application:
    name: ApiGateway
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:81
        heart-beat-interval: 15
        heart-beat-timeout: 60
        register-enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

logging:
  level:
    root: info
    com:
      baomidou: warn
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger- %msg%n'
  file:
    max-history: 30
    name: logs/${spring.application.name}_log.log
    clean-history-on-start: false