server:
  port: 8100

spring:
  application:
    name: ApiGateway
  cloud:
    nacos:
      discovery:
        register-enabled: false
        server-addr: localhost:81
        heart-beat-interval: 15
        heart-beat-timeout: 60
        ip: 127.0.0.1
    gateway:
      discovery:
        locator:
          enabled: true
